### ISSUE TITLE
Specified cast is not valid

### ISSUE THREAD

**Issue by ertejaspatel** [sethreno/schemazen#84] opened 2016-04-14 02:30 UTC
at SchemaZen.model.Database.LoadColumnsBase(IDataReader dr, List`1 tables)
   at SchemaZen.model.Database.LoadColumns(SqlCommand cm)
   at SchemaZen.model.Database.Load()
   at SchemaZen.console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at SchemaZen.console.Program.Main(String[] args)

**Comment by sethreno** [comment] 2016-04-22 14:58
I'm not able to reproduce this. Please provide a script of the object(s) that I can use to reproduce.

**Comment by sethreno** [comment] 2016-06-29 22:08
Closing as I'm not able to reproduce.

**Closed by sethreno** 2016-06-29 22:08 UTC
