### ISSUE TITLE
Getting errors for SQL Server 2016 CTP3

### ISSUE THREAD

**Issue by rangedsp** [sethreno/schemazen#65] opened 2016-02-06 07:39 UTC
Heya,

I'm getting this error when running against SQL Server 2016 CTP3
![image](https://cloud.githubusercontent.com/assets/4970707/12865469/686e5eb4-cd11-11e5-9824-07339910d6db.png)

Would be nice if it's fixed eventually

Cheers,
Jonny

**Comment by sethreno** [comment] 2016-02-11 01:32
Thanks for reporting, but this is a duplicate of #34

**Closed** 2016-02-11 01:33 UTC
Labels: duplicate

**Comment by sethreno** [comment] 2016-02-11 02:36
This should be fixed. Please get the latest version and verify. Thanks!
