### ISSUE TITLE
Unable to cast object of type 'System.DBNull' to type 'System.String'

### ISSUE THREAD

**Issue by ertejaspatel** [sethreno/schemazen#85] opened 2016-04-14 02:30 UTC
Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at SchemaZen.model.Database.LoadColumnDefaults(SqlCommand cm)
   at SchemaZen.model.Database.Load()
   at SchemaZen.console.Script.Run(String[] args)
   at ManyConsole.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut, Boolean skipExeInExpectedUsage)
   at SchemaZen.console.Program.Main(String[] args)

**Comment by ertejaspatel** [comment] 2016-04-14 03:37
I found similar error occur in following methods in Database.cs:
        LoadColumnDefaults(cm);
        LoadColumnComputes(cm);
        LoadCheckConstraints(cm);

**Comment by sethreno** [comment] 2016-04-22 14:56
I'm not able to reproduce this. Please provide a script of the object(s) that I can use to reproduce.

**Comment by sethreno** [comment] 2016-06-29 22:08
closing as I'm not able to reproduce

**Closed by sethreno** 2016-06-29 22:08 UTC
