### ISSUE TITLE
Receiving error when attempting to use the "script" command

### ISSUE THREAD

**Issue by ryanhinton** [sethreno/schemazen#114] opened 2016-12-01 17:06 UTC
sz script --server "bctc9sqld01\appdev" --database "contegolinkdev" --scriptDir "f:\sql\projectdev_schemazen" -u "myusername" -p "mypassword" --filterTypes "data" -o true -v true
Loading database schema...

Unable to cast object of type 'System.DBNull' to type 'System.String'.

'Script' - Generate scripts for the specified database.

**Comment by sethreno** [comment] 2017-01-28 23:35
Can you include the stack trace?

**Comment by sethreno** [comment] 2017-02-01 01:43
I can't reproduce this. Closing for now. If you have more information please respond and I'll reopen.

**Closed by sethreno** 2017-02-01 01:43 UTC
Labels: can't reproduce, script-create
